# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# For SEO, see: https://github.com/jekyll/jekyll-seo-tag
title: Positive Revolution
description: |
  Positive Revolution provides outsourced company culture development. We work with companies and organisations to provide the people balance ensuring they are happy, healthy and love working for the organisations they are with. Located in Cairns, Queensland, we travel throughout Australia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.positiverevolution.com.au" # the base hostname & protocol for your site
assetsurl: "/assets/images/"
phone: 0457 738 099
email: greg@positiverevolution.com.au
logo: "/images/logo.png"
social:
  linkedin: https://au.linkedin.com/in/leadershiptrainerdeveloper
twitter:
  username: callumflack
google-analytics: UA-49604697-1

# Defaults
defaults:
- scope:
    path: ""
    type: posts
  values:
    permalink: "/blog/:categories/:title/"
    layout: article

# Collections
collections:
  uploads:
    title: Uploads
    output: false

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
# Remove the CNAME if using Siteleaf!
exclude:
- assets/_source
- CNAME
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
- README.md
- TODO.md

# Plugin settings
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
