---
title: Positive Revolution
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: article
description: 'Positive Revolution provides outsourced company culture development.
  We work with companies and organisations to provide the people balance ensuring
  they are happy, healthy and love working for the organisations they are with. Located
  in Cairns, Queensland, we travel throughout Australia.

'
baseurl:
url: http://www.positiverevolution.com.au
assetsurl: "/assets/images/"
phone: 0457 738 099
email: greg@positiverevolution.com.au
logo: "/images/logo.png"
social:
  linkedin: https://au.linkedin.com/in/leadershiptrainerdeveloper
twitter:
  username: callumflack
google-analytics: UA-49604697-1
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
- assets/_source
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
- README.md
- TODO.md
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
